import Foundation

enum UILDatasetCatalog {
    static let all: [UILDataset] = [
        .init(slug: "piano", label: "Piano Solos", shortLabel: "piano solo", songsPath: "piano-solos.json", statsPath: "piano-stats.json", section: .solo),
        .init(slug: "band", label: "Band Literature", shortLabel: "band work", songsPath: "band.json", statsPath: "band-stats.json", section: .largeGroup),
        .init(slug: "bb-clarinet-solo", label: "Bb Clarinet Solos", shortLabel: "Bb clarinet solo", songsPath: "bb-clarinet-solos.json", statsPath: "bb-clarinet-stats.json", section: .solo),
        .init(slug: "alto-clarinet-solo", label: "Alto Clarinet Solos", shortLabel: "alto clarinet solo", songsPath: "alto-clarinet-solos.json", statsPath: "alto-clarinet-stats.json", section: .solo),
        .init(slug: "bass-clarinet-solo", label: "Bass Clarinet Solos", shortLabel: "bass clarinet solo", songsPath: "bass-clarinet-solos.json", statsPath: "bass-clarinet-stats.json", section: .solo),
        .init(slug: "eb-clarinet-solo", label: "Eb Clarinet Solos", shortLabel: "Eb clarinet solo", songsPath: "eb-clarinet-solos.json", statsPath: "eb-clarinet-stats.json", section: .solo),
        .init(slug: "contra-bass-clarinet-solo", label: "Contra Bass Clarinet Solos", shortLabel: "contra bass clarinet solo", songsPath: "contra-bass-clarinet-solos.json", statsPath: "contra-bass-clarinet-stats.json", section: .solo),
        .init(slug: "french-horn", label: "French Horn Solos", shortLabel: "french horn solo", songsPath: "french-horn-solos.json", statsPath: "french-horn-stats.json", section: .solo),
        .init(slug: "soprano-saxophone", label: "Soprano Saxophone Solos", shortLabel: "soprano saxophone solo", songsPath: "soprano-saxophone-solos.json", statsPath: "soprano-saxophone-stats.json", section: .solo),
        .init(slug: "tuba", label: "Tuba Solos", shortLabel: "tuba solo", songsPath: "tuba-solos.json", statsPath: "tuba-stats.json", section: .solo),
        .init(slug: "trumpet", label: "Trumpet Solos", shortLabel: "trumpet solo", songsPath: "trumpet-solos.json", statsPath: "trumpet-stats.json", section: .solo),
        .init(slug: "flute", label: "Flute Solos", shortLabel: "flute solo", songsPath: "flute-solos.json", statsPath: "flute-stats.json", section: .solo),
        .init(slug: "oboe", label: "Oboe Solos", shortLabel: "oboe solo", songsPath: "oboe-solos.json", statsPath: "oboe-stats.json", section: .solo),
        .init(slug: "bassoon", label: "Bassoon Solos", shortLabel: "bassoon solo", songsPath: "bassoon-solos.json", statsPath: "bassoon-stats.json", section: .solo),
        .init(slug: "alto-saxophone", label: "Alto Saxophone Solos", shortLabel: "alto saxophone solo", songsPath: "alto-saxophone-solos.json", statsPath: "alto-saxophone-stats.json", section: .solo),
        .init(slug: "tenor-saxophone", label: "Tenor Saxophone Solos", shortLabel: "tenor saxophone solo", songsPath: "tenor-saxophone-solos.json", statsPath: "tenor-saxophone-stats.json", section: .solo),
        .init(slug: "baritone-saxophone", label: "Baritone Saxophone Solos", shortLabel: "baritone saxophone solo", songsPath: "baritone-saxophone-solos.json", statsPath: "baritone-saxophone-stats.json", section: .solo),
        .init(slug: "tenor-trombone", label: "Tenor Trombone Solos", shortLabel: "tenor trombone solo", songsPath: "tenor-trombone-solos.json", statsPath: "tenor-trombone-stats.json", section: .solo),
        .init(slug: "bass-trombone", label: "Bass Trombone Solos", shortLabel: "bass trombone solo", songsPath: "bass-trombone-solos.json", statsPath: "bass-trombone-stats.json", section: .solo),
        .init(slug: "violin", label: "Violin Solos", shortLabel: "violin solo", songsPath: "violin-solos.json", statsPath: "violin-stats.json", section: .solo),
        .init(slug: "viola", label: "Viola Solos", shortLabel: "viola solo", songsPath: "viola-solos.json", statsPath: "viola-stats.json", section: .solo),
        .init(slug: "cello", label: "Cello Solos", shortLabel: "cello solo", songsPath: "cello-solos.json", statsPath: "cello-stats.json", section: .solo),
        .init(slug: "string-bass", label: "String Bass Solos", shortLabel: "string bass solo", songsPath: "string-bass-solos.json", statsPath: "string-bass-stats.json", section: .solo),
        .init(slug: "euphonium", label: "Euphonium and Baritone Horn Solos", shortLabel: "euphonium solo", songsPath: "euphonium-solos.json", statsPath: "euphonium-stats.json", section: .solo),
        .init(slug: "piccolo", label: "Piccolo Solos", shortLabel: "piccolo solo", songsPath: "piccolo-solos.json", statsPath: "piccolo-stats.json", section: .solo),
        .init(slug: "english-horn", label: "English Horn Solos", shortLabel: "English horn solo", songsPath: "english-horn-solos.json", statsPath: "english-horn-stats.json", section: .solo),
        .init(slug: "snare-drum", label: "Snare Drum Solos", shortLabel: "snare drum solo", songsPath: "snare-drum-solos.json", statsPath: "snare-drum-stats.json", section: .solo),
        .init(slug: "timpani", label: "Timpani Solos", shortLabel: "timpani solo", songsPath: "timpani-solos.json", statsPath: "timpani-stats.json", section: .solo),
        .init(slug: "keyboard-percussion", label: "Keyboard Percussion Solos", shortLabel: "keyboard percussion solo", songsPath: "keyboard-percussion-solos.json", statsPath: "keyboard-percussion-stats.json", section: .solo),
        .init(slug: "multiple-percussion", label: "Multiple Percussion Solos", shortLabel: "multiple percussion solo", songsPath: "multiple-percussion-solos.json", statsPath: "multiple-percussion-stats.json", section: .solo),
        .init(slug: "drum-set", label: "Drum Set Solos", shortLabel: "drum set solo", songsPath: "drum-set-solos.json", statsPath: "drum-set-stats.json", section: .solo),
        .init(slug: "steel-pan", label: "Steel Pan Solos", shortLabel: "steel pan solo", songsPath: "steel-pan-solos.json", statsPath: "steel-pan-stats.json", section: .solo),
        .init(slug: "woodwind-trio", label: "Woodwind Trios", shortLabel: "woodwind trio", songsPath: "woodwind-trio.json", statsPath: "woodwind-trio-stats.json", section: .ensemble),
        .init(slug: "flute-trio", label: "Flute Trios", shortLabel: "flute trio", songsPath: "flute-trio.json", statsPath: "flute-trio-stats.json", section: .ensemble),
        .init(slug: "bb-clarinet-trio", label: "Bb Clarinet Trios", shortLabel: "Bb clarinet trio", songsPath: "bb-clarinet-trio.json", statsPath: "bb-clarinet-trio-stats.json", section: .ensemble),
        .init(slug: "mixed-clarinet-trio", label: "Mixed Clarinet Trios", shortLabel: "mixed clarinet trio", songsPath: "mixed-clarinet-trio.json", statsPath: "mixed-clarinet-trio-stats.json", section: .ensemble),
        .init(slug: "woodwind-quartet", label: "Woodwind Quartets", shortLabel: "woodwind quartet", songsPath: "woodwind-quartet.json", statsPath: "woodwind-quartet-stats.json", section: .ensemble),
        .init(slug: "flute-quartet", label: "Flute Quartets", shortLabel: "flute quartet", songsPath: "flute-quartet.json", statsPath: "flute-quartet-stats.json", section: .ensemble),
        .init(slug: "bb-clarinet-quartet", label: "Bb Clarinet Quartets", shortLabel: "Bb clarinet quartet", songsPath: "bb-clarinet-quartet.json", statsPath: "bb-clarinet-quartet-stats.json", section: .ensemble),
        .init(slug: "mixed-clarinet-quartet", label: "Mixed Clarinet Quartets", shortLabel: "mixed clarinet quartet", songsPath: "mixed-clarinet-quartet.json", statsPath: "mixed-clarinet-quartet-stats.json", section: .ensemble),
        .init(slug: "saxophone-quartet", label: "Saxophone Quartets", shortLabel: "saxophone quartet", songsPath: "saxophone-quartet.json", statsPath: "saxophone-quartet-stats.json", section: .ensemble),
        .init(slug: "woodwind-quintet", label: "Woodwind Quintets", shortLabel: "woodwind quintet", songsPath: "woodwind-quintet.json", statsPath: "woodwind-quintet-stats.json", section: .ensemble),
        .init(slug: "misc-woodwind-ensemble", label: "Miscellaneous Woodwind Ensembles", shortLabel: "woodwind ensemble", songsPath: "misc-woodwind-ensemble.json", statsPath: "misc-woodwind-ensemble-stats.json", section: .ensemble),
        .init(slug: "double-reed-ensemble", label: "Double Reed Ensembles", shortLabel: "double reed ensemble", songsPath: "double-reed-ensemble.json", statsPath: "double-reed-ensemble-stats.json", section: .ensemble),
        .init(slug: "flute-choir", label: "Flute Choirs", shortLabel: "flute choir work", songsPath: "flute-choir.json", statsPath: "flute-choir-stats.json", section: .largeGroup),
        .init(slug: "clarinet-choir", label: "Clarinet Choirs", shortLabel: "clarinet choir work", songsPath: "clarinet-choir.json", statsPath: "clarinet-choir-stats.json", section: .largeGroup),
        .init(slug: "misc-saxophone-ensemble", label: "Miscellaneous Saxophone Ensembles", shortLabel: "saxophone ensemble", songsPath: "misc-saxophone-ensemble.json", statsPath: "misc-saxophone-ensemble-stats.json", section: .ensemble),
        .init(slug: "trumpet-trio", label: "Trumpet Trios", shortLabel: "trumpet trio", songsPath: "trumpet-trio.json", statsPath: "trumpet-trio-stats.json", section: .ensemble),
        .init(slug: "trombone-trio", label: "Trombone Trios", shortLabel: "trombone trio", songsPath: "trombone-trio.json", statsPath: "trombone-trio-stats.json", section: .ensemble),
        .init(slug: "euphonium-baritone-trio", label: "Euphonium-Baritone Trios", shortLabel: "euphonium trio", songsPath: "euphonium-baritone-trio.json", statsPath: "euphonium-baritone-trio-stats.json", section: .ensemble),
        .init(slug: "brass-trio", label: "Brass Trios", shortLabel: "brass trio", songsPath: "brass-trio.json", statsPath: "brass-trio-stats.json", section: .ensemble),
        .init(slug: "trumpet-quartet", label: "Trumpet Quartets", shortLabel: "trumpet quartet", songsPath: "trumpet-quartet.json", statsPath: "trumpet-quartet-stats.json", section: .ensemble),
        .init(slug: "horn-quartet", label: "Horn Quartets", shortLabel: "horn quartet", songsPath: "horn-quartet.json", statsPath: "horn-quartet-stats.json", section: .ensemble),
        .init(slug: "euphonium-baritone-quartet", label: "Euphonium and Baritone Horn Quartets", shortLabel: "euphonium quartet", songsPath: "euphonium-baritone-quartet.json", statsPath: "euphonium-baritone-quartet-stats.json", section: .ensemble),
        .init(slug: "brass-quartet", label: "Brass Quartets", shortLabel: "brass quartet", songsPath: "brass-quartet.json", statsPath: "brass-quartet-stats.json", section: .ensemble),
        .init(slug: "trombone-quartet", label: "Trombone Quartets", shortLabel: "trombone quartet", songsPath: "trombone-quartet.json", statsPath: "trombone-quartet-stats.json", section: .ensemble),
        .init(slug: "tuba-euphonium-quartet", label: "Tuba and Euphonium Quartets", shortLabel: "tuba/euphonium quartet", songsPath: "tuba-euphonium-quartet.json", statsPath: "tuba-euphonium-quartet-stats.json", section: .ensemble),
        .init(slug: "brass-quintet", label: "Brass Quintets", shortLabel: "brass quintet", songsPath: "brass-quintet.json", statsPath: "brass-quintet-stats.json", section: .ensemble),
        .init(slug: "brass-sextet", label: "Brass Sextets", shortLabel: "brass sextet", songsPath: "brass-sextet.json", statsPath: "brass-sextet-stats.json", section: .ensemble),
        .init(slug: "six-or-more-brass", label: "Six or More Brass Ensembles", shortLabel: "brass ensemble", songsPath: "six-or-more-brass.json", statsPath: "six-or-more-brass-stats.json", section: .ensemble),
        .init(slug: "trumpet-choir", label: "Trumpet Choirs", shortLabel: "trumpet choir work", songsPath: "trumpet-choir.json", statsPath: "trumpet-choir-stats.json", section: .largeGroup),
        .init(slug: "misc-horn-ensemble", label: "Miscellaneous Horn Ensembles", shortLabel: "horn ensemble", songsPath: "misc-horn-ensemble.json", statsPath: "misc-horn-ensemble-stats.json", section: .ensemble),
        .init(slug: "trombone-choir", label: "Trombone Choirs", shortLabel: "trombone choir work", songsPath: "trombone-choir.json", statsPath: "trombone-choir-stats.json", section: .largeGroup),
        .init(slug: "percussion-ensemble", label: "Percussion Ensembles", shortLabel: "percussion ensemble", songsPath: "percussion-ensemble.json", statsPath: "percussion-ensemble-stats.json", section: .ensemble),
        .init(slug: "steel-band", label: "Steel Bands", shortLabel: "steel band work", songsPath: "steel-band.json", statsPath: "steel-band-stats.json", section: .largeGroup),
        .init(slug: "misc-mixed-ensemble", label: "Miscellaneous Mixed Ensembles", shortLabel: "mixed ensemble", songsPath: "misc-mixed-ensemble.json", statsPath: "misc-mixed-ensemble-stats.json", section: .ensemble),
        .init(slug: "acoustical-guitar", label: "Acoustical Guitar Solos", shortLabel: "acoustical guitar solo", songsPath: "acoustical-guitar-solos.json", statsPath: "acoustical-guitar-stats.json", section: .solo),
        .init(slug: "piano-trio", label: "Piano Trios", shortLabel: "piano trio", songsPath: "piano-trio.json", statsPath: "piano-trio-stats.json", section: .ensemble),
        .init(slug: "violin-trio", label: "Violin Trios", shortLabel: "violin trio", songsPath: "violin-trio.json", statsPath: "violin-trio-stats.json", section: .ensemble),
        .init(slug: "string-trio", label: "String Trios", shortLabel: "string trio", songsPath: "string-trio.json", statsPath: "string-trio-stats.json", section: .ensemble),
        .init(slug: "misc-string-trio", label: "Miscellaneous String Trios", shortLabel: "string trio", songsPath: "misc-string-trio.json", statsPath: "misc-string-trio-stats.json", section: .ensemble),
        .init(slug: "guitar-trio", label: "Guitar Trios", shortLabel: "guitar trio", songsPath: "guitar-trio.json", statsPath: "guitar-trio-stats.json", section: .ensemble),
        .init(slug: "violin-quartets", label: "Violin Quartets", shortLabel: "violin quartet", songsPath: "violin-quartets.json", statsPath: "violin-quartets-stats.json", section: .ensemble),
        .init(slug: "string-quartet", label: "String Quartets", shortLabel: "string quartet", songsPath: "string-quartet.json", statsPath: "string-quartet-stats.json", section: .ensemble),
        .init(slug: "misc-string-quartet", label: "Miscellaneous String Quartets", shortLabel: "string quartet", songsPath: "misc-string-quartet.json", statsPath: "misc-string-quartet-stats.json", section: .ensemble),
        .init(slug: "guitar-quartet", label: "Guitar Quartets", shortLabel: "guitar quartet", songsPath: "guitar-quartet.json", statsPath: "guitar-quartet-stats.json", section: .ensemble),
        .init(slug: "string-quintet", label: "String Quintets", shortLabel: "string quintet", songsPath: "string-quintet.json", statsPath: "string-quintet-stats.json", section: .ensemble),
        .init(slug: "misc-string-quintet", label: "Miscellaneous String Quintets", shortLabel: "string quintet", songsPath: "misc-string-quintet.json", statsPath: "misc-string-quintet-stats.json", section: .ensemble),
        .init(slug: "misc-string-ensemble", label: "Miscellaneous String Ensembles", shortLabel: "string ensemble", songsPath: "misc-string-ensemble.json", statsPath: "misc-string-ensemble-stats.json", section: .ensemble),
        .init(slug: "misc-guitar-ensemble", label: "Miscellaneous Guitar Ensembles", shortLabel: "guitar ensemble", songsPath: "misc-guitar-ensemble.json", statsPath: "misc-guitar-ensemble-stats.json", section: .ensemble),
        .init(slug: "cello-choir", label: "Cello Choirs", shortLabel: "cello choir work", songsPath: "cello-choir.json", statsPath: "cello-choir-stats.json", section: .largeGroup),
        .init(slug: "harp", label: "Harp Solos", shortLabel: "harp solo", songsPath: "harp-solos.json", statsPath: "harp-stats.json", section: .solo),
        .init(slug: "harp-ensemble", label: "Harp Ensembles", shortLabel: "harp ensemble", songsPath: "harp-ensemble.json", statsPath: "harp-ensemble-stats.json", section: .ensemble),
        .init(slug: "full-orchestra", label: "Full Orchestra", shortLabel: "full orchestra work", songsPath: "full-orchestra.json", statsPath: "full-orchestra-stats.json", section: .largeGroup),
        .init(slug: "string-orchestra", label: "String Orchestra", shortLabel: "string orchestra work", songsPath: "string-orchestra.json", statsPath: "string-orchestra-stats.json", section: .largeGroup),
        .init(slug: "vocal", label: "Vocal Solos", shortLabel: "vocal solo", songsPath: "vocal-solos.json", statsPath: "vocal-stats.json", section: .solo),
        .init(slug: "treble-small-ensemble", label: "Treble Small Ensembles", shortLabel: "treble ensemble", songsPath: "treble-small-ensemble.json", statsPath: "treble-small-ensemble-stats.json", section: .ensemble),
        .init(slug: "tenor-bass-small-ensemble", label: "Tenor-Bass Small Ensembles", shortLabel: "tenor-bass ensemble", songsPath: "tenor-bass-small-ensemble.json", statsPath: "tenor-bass-small-ensemble-stats.json", section: .ensemble),
        .init(slug: "madrigal", label: "Madrigals", shortLabel: "madrigal", songsPath: "madrigal.json", statsPath: "madrigal-stats.json", section: .largeGroup),
        .init(slug: "mixed-chorus", label: "Mixed Choruses", shortLabel: "mixed chorus work", songsPath: "mixed-chorus.json", statsPath: "mixed-chorus-stats.json", section: .largeGroup),
        .init(slug: "tenor-bass-chorus", label: "Tenor-Bass Choruses", shortLabel: "tenor-bass chorus work", songsPath: "tenor-bass-chorus.json", statsPath: "tenor-bass-chorus-stats.json", section: .largeGroup),
        .init(slug: "treble-chorus", label: "Treble Choruses", shortLabel: "treble chorus work", songsPath: "treble-chorus.json", statsPath: "treble-chorus-stats.json", section: .largeGroup),
    ]

    static let grouped: [(section: UILDataset.Section, datasets: [UILDataset])] = UILDataset.Section.allCases.map { section in
        let datasets = all
            .filter { $0.section == section }
            .sorted { $0.label.localizedCaseInsensitiveCompare($1.label) == .orderedAscending }
        return (section, datasets)
    }
}
